### ISSUE TITLE
Impossible to create View holder Issue.

### ISSUE THREAD

**Issue by umair088** [StanKocken/EfficientAdapter#16] opened 2015-09-09 22:46 UTC
I am getting this error in binding the list.could not understand what's wrong with it can u tell me what's the reason of error which you handled?

**Comment by StanKocken** [comment] 2015-09-10 08:11
Can you give more detail on your error please?

**Comment by brucetoo** [comment] 2015-11-16 10:47
May be umair088 use ViewHolder as inner class

**Comment by StanKocken** [comment] 2015-11-16 10:48
@brucetoo and you noticed that is not supported?

**Comment by brucetoo** [comment] 2015-11-16 10:52
Yup,  you can reproduce like this demo code:
 ```
public class MainActivity extends AppCompatActivity {

    @Bind(R.id.recycler_view)
    RecyclerView mRecyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_simple_demo);
        ButterKnife.bind(this);

        EfficientRecyclerAdapter<String> adapter = new EfficientRecyclerAdapter<>(R.layout.layout_demo_item,
                ItemViewHolder.class, getDatas());
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mRecyclerView.setAdapter(adapter);
    }

    private List<String> getDatas() {
        List<String> list = new ArrayList<>();
        for (int i = 0; i < 20; i++) {
            list.add("recycleritem：" + i);
        }
        return list;
    }


    public class ItemViewHolder extends EfficientViewHolder<String> {
        public ItemViewHolder(View itemView) {
            super(itemView);
        }

        @Override
        protected void updateView(Context context, String object) {
            TextView textView = findViewByIdEfficient(R.id.tv_desc);
            textView.setText(object);
        }
    }
}

```


Then you will see IllegalArgumentException like this:

```
java.lang.IllegalArgumentException: Impossible to found a constructor with a view for ItemViewHolder

```

**Comment by StanKocken** [comment] 2015-11-16 11:07
Oh okay, I see. I'm not sure if it's a good idea to fix this crash, it's a big source of leak.

Your inner class needs to be static, so you need to change your

    public class ItemViewHolder extends EfficientViewHolder<String> {

to

    public static class ItemViewHolder extends EfficientViewHolder<String> {

And it will fix your crash.

**Comment by brucetoo** [comment] 2015-11-16 11:12
Yeah,I know how to fix,By the way,it's a great lib

**Comment by StanKocken** [comment] 2015-11-16 11:19
Thanks.

@umair088 I will close this issue because I didn't receive any new information from you. Feel free to reach me if you can give me more detail.

**Closed by StanKocken** 2015-11-16 11:19 UTC
